name: CyVerse Datastore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and install GoCommands
      run: |
        GOCMD_VER=$(curl -L -s https://raw.githubusercontent.com/cyverse/gocommands/main/VERSION.txt)
        curl -L -s https://github.com/cyverse/gocommands/releases/download/${GOCMD_VER}/gocmd-${GOCMD_VER}-linux-amd64.tar.gz | tar zxvf -
        sudo mv gocmd /usr/local/bin/

    - name: Upload folder to CyVerse
      env:
        IRODS_USER_NAME: ${{ secrets.CYVERSE_USERNAME }}
        IRODS_USER_PASSWORD: ${{ secrets.CYVERSE_PASSWORD }}
        IRODS_HOST: data.cyverse.org
        IRODS_PORT: 1247
        IRODS_ZONE_NAME: iplant
      run: |
        gocmd put --force --progress test_folder2 /iplant/home/${{secrets.CYVERSE_USERNAME}}/
      
