name: CyVerse Datastore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and install GoCommands
      run: |
        GOCMD_VER=$(curl -L -s https://raw.githubusercontent.com/cyverse/gocommands/main/VERSION.txt)
        curl -L -s https://github.com/cyverse/gocommands/releases/download/${GOCMD_VER}/gocmd-${GOCMD_VER}-linux-amd64.tar.gz | tar zxvf -
        sudo mv gocmd /usr/local/bin/

    - name: Set up CyVerse credentials
      run: |
        echo "export CYVERSE_USERNAME=${{ secrets.CYVERSE_USERNAME }}" >> $GITHUB_ENV
        echo "export CYVERSE_PASSWORD=${{ secrets.CYVERSE_PASSWORD }}" >> $GITHUB_ENV

    - name: Run Python script
      run: |
        python script.py
