name: CyVerse Datastore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and install GoCommands
      run: |
        GOCMD_VER=$(curl -L -s https://raw.githubusercontent.com/cyverse/gocommands/main/VERSION.txt)
        curl -L -s https://github.com/cyverse/gocommands/releases/download/${GOCMD_VER}/gocmd-${GOCMD_VER}-linux-amd64.tar.gz | tar zxvf -
        sudo mv gocmd /usr/local/bin/

    - name: Set up CyVerse credentials
      env:
        CYVERSE_USERNAME: ${{ secrets.CYVERSE_USERNAME }}
        CYVERSE_PASSWORD: ${{ secrets.CYVERSE_PASSWORD }}
      run: |
        mkdir -p ~/.irods
        cat <<EOF > ~/.irods/irods_environment.json
        {
          "irods_host": "data.cyverse.org",
          "irods_port": 1247,
          "irods_user_name": "${{ secrets.CYVERSE_USERNAME }}",
          "irods_zone_name": "iplant",
          "irods_user_password": "${{ secrets.CYVERSE_PASSWORD }}"
        }
        EOF

    - name: Upload to CyVerse
      run: |
        gocmd put --force --progress test_folder2 /iplant/home/${{secrets.CYVERSE_USERNAME}}/
